name: Salesforce Sandbox Refresh and Dockerize

on:
  push:
    branches:
      - main

jobs:
  refresh-sandbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          tar xJf sfdx-linux-amd64.tar.xz --directory /usr/local --strip-components 1

      - name: Authenticate to Salesforce using Device Code
        id: auth
        run: |
          sf org login device --set-default-dev-hub --alias ${{ secrets.SF_ORG_ALIAS }}

      - name: Refresh Sandbox
        run: |
          sfdx force:org:delete -u ${{ secrets.SF_ORG_ALIAS }} -p
          sfdx force:org:create -f config/project-scratch-def.json -a ${{ secrets.SF_ORG_ALIAS }}

      - name: Create Docker Image
        run: |
          docker build -t salesforce-sandbox:latest .

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: |
          docker tag salesforce-sandbox:latest ${{ secrets.DOCKER_USERNAME }}/salesforce-sandbox:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/salesforce-sandbox:latest
