name: Salesforce Sandbox Refresh and Dockerize

on:
  push:
    branches:
      - main

jobs:
  refresh-sandbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set timezone non-interactively
        run: |
          echo "Setting timezone to Etc/UTC"
          echo 'Etc/UTC' | sudo tee /etc/timezone
          sudo dpkg-reconfigure -f noninteractive tzdata

      - name: Install Salesforce CLI
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.gz -O /tmp/sf-linux-x64.tar.gz
            sudo mkdir -p /usr/local/sf
            sudo tar -xzf /tmp/sf-linux-x64.tar.gz -C /usr/local/sf --strip-components=1
            sudo ln -s /usr/local/sf/bin/sf /usr/local/bin/sf
            rm /tmp/sf-linux-x64.tar.gz


      - name: Authenticate to Salesforce using JWT
        env:
              SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
              SF_USERNAME: ${{ secrets.SF_USERNAME }}
              SF_JWT_KEY: ${{ secrets.SERVERKEY }}
              SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
        run: |
          echo "${{ secrets.SERVERKEY }}" > server.key
          sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }} --instance-url ${{ secrets.SF_INSTANCE_URL }}


      - name: Refresh Sandbox
        run: |
            sf update
            sf org refresh sandbox --name EndofMonth --target-org peerless1234

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
            docker build --build-arg DEBIAN_FRONTEND=noninteractive --build-arg TZ=Etc/UTC -t ${{ secrets.DOCKER_USERNAME }}/salesforcesandbox:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/salesforcesandbox:latest

      - name: Check image
        run: docker images
