name: Salesforce Sandbox Refresh and Dockerize

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add this line to enable manual triggers

jobs:
  refresh-sandbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set timezone non-interactively
        run: |
          echo "Setting timezone to Etc/UTC"
          echo 'Etc/UTC' | sudo tee /etc/timezone
          sudo dpkg-reconfigure -f noninteractive tzdata

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.gz -O /tmp/sf-linux-x64.tar.gz
          sudo mkdir -p /usr/local/sf
          sudo tar -xzf /tmp/sf-linux-x64.tar.gz -C /usr/local/sf --strip-components=1
          sudo ln -s /usr/local/sf/bin/sf /usr/local/bin/sf
          rm /tmp/sf-linux-x64.tar.gz

      - name: Authenticate to Salesforce using JWT
        env:
          SF_CONSUMER_KEY: ${{ github.event.inputs.SF_CONSUMER_KEY }}
          SF_USERNAME: ${{ github.event.inputs.SF_USERNAME }}
          SF_JWT_KEY: ${{ github.event.inputs.SF_JWT_KEY }}
          SF_INSTANCE_URL: ${{ github.event.inputs.SF_INSTANCE_URL }}
        run: |
          echo "${{ github.event.inputs.SF_JWT_KEY }}" > server.key
          sf org login jwt --client-id ${{ github.event.inputs.SF_CONSUMER_KEY }} --jwt-key-file server.key --username ${{ github.event.inputs.SF_USERNAME }} --instance-url ${{ github.event.inputs.SF_INSTANCE_URL }} --alias ${{ github.event.inputs.SF_ORG_ALIAS }} --set-default

      - name: Refresh Sandbox
        run: |
          sf update
          sf org list
          sf org refresh sandbox --name ${{ github.event.inputs.SANDBOXNAME }} --target-org ${{ github.event.inputs.SF_ORG_ALIAS }} --no-prompt -w 1440

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.DOCKER_USERNAME }}
          password: ${{ github.event.inputs.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          docker build --build-arg DEBIAN_FRONTEND=noninteractive --build-arg TZ=Etc/UTC -t ${{ github.event.inputs.DOCKER_USERNAME }}/salesforcesandbox:latest .
          docker push ${{ github.event.inputs.DOCKER_USERNAME }}/salesforcesandbox:latest

      - name: Check image
        run: docker images
